package tech.nimbbl.coreapisdk.models

data class OrderResponse(
    val additional_charges: Double,
    val address: Address,
    val amount_before_tax: Double,
    val attempts: Int,
    val browser_name: String,
    val callback_mode: String,
    val callback_url: String,
    val cancellation_reason: Any,
    val currency: String,
    val description: Any,
    val device_name: String,
    val device_user_agent: String,
    val fingerprint: Any,
    val grand_total_amount: Double,
    val invoice_id: String,
    val max_retries: Int,
    val merchant_shopfront_domain: String,
    val order_date: String,
    val order_from_ip: String,
    val order_id: String,
    val order_line_item: List<OrderLineItem>,
    val order_transac_type: Any,
    val os_name: String,
    val partner_id: Any,
    val referrer_platform: Any,
    val referrer_platform_version: Any,
    val status: String,
    val sub_merchant: SubMerchant,
    val sub_merchant_id: Int,
    val tax: Double,
    val total_amount: Double,
    val user: User
)